import '../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative h-screen w-screnn bg-[#333] flex justify-center items-center text-[#f6f2f3]'>{children}</body>
    </html>
  )
}
